from __future__ import annotations
import json
import os
import re
from pathlib import Path
from typing import Any, Dict, List

BASE_DIR = Path(__file__).resolve().parent
DATA_DIR = BASE_DIR.parent / 'src' / 'assets' / 'data'
OPENAI_API_KEY = os.environ.get('OPENAI_API_KEY')


def load_game_documents() -> List[Dict[str, str]]:
    documents: List[Dict[str, str]] = []

    if not DATA_DIR.exists():
        raise FileNotFoundError(f'Game data directory not found: {DATA_DIR}')

    for file_path in sorted(DATA_DIR.glob('*.json')):
        try:
            raw = json.loads(file_path.read_text(encoding='utf-8'))
            documents.extend(flatten_game_data(file_path.stem, raw))
        except json.JSONDecodeError:
            continue

    return documents


def flatten_game_data(source: str, data: Any) -> List[Dict[str, str]]:
    if data is None:
        return []

    if isinstance(data, list):
        return [
            {
                'id': f'{source}-{index}',
                'text': object_to_text(item),
            }
            for index, item in enumerate(data, start=1)
        ]

    if isinstance(data, dict):
        return [
            {
                'id': source,
                'text': object_to_text(data),
            }
        ]

    return [{'id': source, 'text': object_to_text(data)}]


def object_to_text(value: Any) -> str:
    if value is None:
        return ''
    if isinstance(value, (str, int, float, bool)):
        return str(value)
    if isinstance(value, list):
        return ' '.join(object_to_text(item) for item in value)
    if isinstance(value, dict):
        return ' | '.join(f'{key}: {object_to_text(val)}' for key, val in value.items())
    return str(value)


class SimpleRetriever:
    def __init__(self, documents: List[Dict[str, str]]) -> None:
        self.documents = documents

    async def retrieve(self, query: str, limit: int = 5) -> List[Dict[str, Any]]:
        query_text = normalize_text(query)
        scored = [
            {
                'id': doc['id'],
                'text': doc['text'],
                'score': score_document(query_text, normalize_text(doc['text'])),
            }
            for doc in self.documents
        ]

        hits = sorted([doc for doc in scored if doc['score'] > 0], key=lambda item: item['score'], reverse=True)
        return hits[:limit]


def normalize_text(text: str) -> str:
    return re.sub(r'[^a-z0-9\s]', ' ', text.lower()).strip()


def score_document(query: str, text: str) -> int:
    if not query or not text:
        return 0

    query_tokens = [token for token in query.split() if token]
    score = sum(1 for token in query_tokens if token in text)
    return score


class PromptTemplate:
    TEMPLATE = (
        'You are an English Fantasy game assistant. Use the game knowledge below to answer the player clearly.\n\n'
        'Game context:\n{context}\n\n'
        'Player question: {query}\n\nAnswer:'
    )

    @classmethod
    def format(cls, query: str, context: str) -> str:
        return cls.TEMPLATE.format(query=query, context=context or 'No relevant game context found.')


class LangChain:
    def __init__(self, retriever: SimpleRetriever) -> None:
        self.retriever = retriever

    async def run(self, query: str) -> str:
        hits = await self.retriever.retrieve(query)
        context = '\n\n'.join(f"- {hit['id']}: {hit['text']}" for hit in hits)
        prompt = PromptTemplate.format(query=query, context=context)
        return await generate_llm_response(prompt)


async def generate_llm_response(prompt: str) -> str:
    if OPENAI_API_KEY and _has_openai():
        return await _openai_response(prompt)
    return simulate_llm_response(prompt)


def _has_openai() -> bool:
    try:
        import openai

        return True
    except ImportError:
        return False


async def _openai_response(prompt: str) -> str:
    import openai

    openai.api_key = OPENAI_API_KEY
    response = openai.ChatCompletion.create(
        model='gpt-3.5-turbo',
        messages=[
            {'role': 'system', 'content': 'You are an English Fantasy tutoring assistant.'},
            {'role': 'user', 'content': prompt},
        ],
        max_tokens=300,
    )
    return response.choices[0].message.content.strip()


def simulate_llm_response(prompt: str) -> str:
    placeholder = (
        '[[Python AI placeholder response]]\n'
        'This demo response is generated by the Python backend.\n'
        'Set OPENAI_API_KEY to use a real LLM.\n\n'
        f'Prompt used:\n{prompt}'
    )
    return placeholder


class GameAgent:
    def __init__(self, chain: LangChain) -> None:
        self.chain = chain

    async def respond(self, player_input: str) -> str:
        return await self.chain.run(player_input)

    async def explain_vocabulary(self, term: str) -> str:
        return await self.chain.run(f'Explain the meaning of the word "{term}" in the context of English Fantasy.')

    async def guide_story(self, topic: str) -> str:
        return await self.chain.run(f'Provide a story-driven description or advice about {topic} using game data.')


async def create_game_agent() -> GameAgent:
    documents = await load_game_documents()
    retriever = SimpleRetriever(documents)
    chain = LangChain(retriever)
    return GameAgent(chain)
